version: "3.2"
services:
  sdc:
    # replace username/repo:tag with your name and image details
    image: streamsets/datacollector:3.1.0.0
    ports:
      - "18630:18630"
    networks:
      - sdcnet
    volumes:
      - ./data:/data
      - ./systemstagelibs:/opt/streamsets-datacollector-3.1.0.0/streamsets-libs
      - ./etc/sdc/sdc-security.policy:/etc/sdc/sdc-security.policy
      - ./userstagelibs:/opt/streamsets-datacollector-3.1.0.0/streamsets-libs-extras/streamsets-datacollector-cdh_5_13-lib/lib
    
networks:
  sdcnet: